server: 
  port: 11500

spring:
  application:
    name: alien-turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:11400/eureka/
# actuator 2.x 以后endpoints 全部在/actuator下，可以通过management.endpoints.web.base-path修改         
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

turbine:
  app-config: alien-zuul,alien-consumer
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
  combine-host: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream